name: Nix flake check
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths:
      - "**/*.nix"
      - "**/flake.nix"
      - "**/flake.lock"

concurrency:
  group: ${{ github.workflow_ref }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  flake-check:
    uses: cffnpwr/actions/.github/workflows/flake-check.yaml@7697aea4419bb4364a48b2d077199624ead433d4
    permissions:
      contents: read
