name: Status check
on:
  pull_request_target: # zizmor: ignore[dangerous-triggers]
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened
      - edited

concurrency:
  group: ${{ github.workflow_ref }}-${{ github.event.number }}
  cancel-in-progress: true

permissions: {}

jobs:
  status-check:
    uses: cffnpwr/actions/.github/workflows/status-check.yaml@7697aea4419bb4364a48b2d077199624ead433d4
    permissions:
      pull-requests: read
      checks: read
      statuses: read
    with:
      timeout-minutes: 300
